spring:
  application:
    name: common-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lqw1111/springcloud-config.git
    bus:
      refresh:
        enabled: true  # 开启自动刷新
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh  #在Greewitch.SR2版中需要开启
